services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8080:8080"
    networks:
      - my-network

  service2:
    build:
      context: ./service
      dockerfile: Dockerfile2
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
